Add kitty configuration

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -5,7 +5,7 @@
 shopt -s dotglob
 
 BACKUP_DIR="$HOME/.config_backup/$(date +%Y%m%d%H%M%S)"
-AVAILABLE_CONFIGS=(bash git i3 idea powerline termite tmux xresources ranger all)
+AVAILABLE_CONFIGS=(bash git i3 idea powerline termite tmux xresources ranger kitty st all)
 declare -A COPY_OPTIONS=(
   # bash
   ["bash_.bash_profile"]="$HOME/.bash_profile"
@@ -39,6 +39,8 @@ declare -A COPY_OPTIONS=(
   # vscode
   ["vscode_settings.json"]="$HOME/.config/Code/User/settings.json"
   ["vscode_keybindings.json"]="$HOME/.config/Code/User/keybindings.json"
+  # kitty
+  ["kitty_kitty.conf"]="$HOME/.config/kitty/kitty.conf"
 )
 
 # Prints help
@@ -204,6 +206,9 @@ while getopts ':hdc:vi:' OPTION; do
     :)
       echo 'Invalid option' >&2
       ;;
+    *)
+      echo 'Invalid option' >&2
+      ;;
   esac
 done
 
@@ -225,7 +230,7 @@ if [[ $install = true ]] || [[ $import = true ]]; then
   valid_config_name=false
   for config_name in "${AVAILABLE_CONFIGS[@]}"
   do
-    if [[ $config_name = $config ]]; then
+    if [[ $config_name = "$config" ]]; then
       valid_config_name=true
       break
     fi
@@ -247,11 +252,11 @@ if [[ $config = 'all' ]]; then
     else
       [[ $safe_install = true ]] && [[ $install = true ]] && backup $config_name
       [[ $install = true ]] && install $config_name
-      [[ $import = true ]] && import $config_name 
+      [[ $import = true ]] && import $config_name
     fi
   done
 else # perform task for only one configuration
   [[ $safe_install = true ]] && [[ $install = true ]] && backup $config
   [[ $install = true ]] && install $config
-  [[ $import = true ]] && import $config 
+  [[ $import = true ]] && import $config
 fi
